Feature/4139 - Forgot password full screen implementation
etn-ccis/blui-react-workflows pull request #303
Opened 2023-06-09 11:05 UTC by manojleaton

Fixes #[BLUI-4139](https://jira-prod.tcc.etn.com/browse/BLUI-4139) .

#### Changes proposed in this Pull Request:

- Added Forgot Password Full Screen 
- Added in the Example2

#### Screenshots / Screen Recording (if applicable)

<img width="1440" alt="Screenshot 2023-06-09 at 4 21 39 PM" src="https://github.com/etn-ccis/blui-react-workflows/assets/130662346/7840063a-7609-4111-8e22-7c9da55343ea">

#### To Test:

- yarn start:example2
- Click on Forgot Password Full Screen button

#### Any specific feedback you are looking for?

-

2023-06-14 10:33 UTC, ektaghag-eaton reviewed
Changes are working fine 👍 .

<img width="677" alt="Screenshot 2023-06-14 at 4 02 27 PM" src="https://github.com/etn-ccis/blui-react-workflows/assets/133877691/a74db1d3-3a5a-4db1-935e-e0ece1dc2e6f">
<img width="609" alt="Screenshot 2023-06-14 at 4 02 18 PM" src="https://github.com/etn-ccis/blui-react-workflows/assets/133877691/2fd295a1-53dc-418c-bed4-7053e0ad9b91">

2023-06-14 10:35 UTC, ektaghag-eaton requested changes
Rename ForgotPasswordFullScreen.tsx to ForgotPasswordScreen.tsx

2023-06-14 14:51 UTC, manojleaton commented
I have Renamed ForgotPasswordFullScreen.tsx to ForgotPasswordScreenTest.tsx as I created screen component file with the name ForgotPasswordScreen.tsx in react-auth-workflow.

2023-06-14 17:14 UTC, daileytj commented on login-workflow/src/new-architecture/screens/ForgotPasswordScreen/ForgotPasswordScreen.tsx
> +        contactPhone = '1-800-123-4567',
This should be a prop that the end user can pass in

2023-06-14 17:15 UTC, daileytj commented on login-workflow/src/new-architecture/screens/ForgotPasswordScreen/ForgotPasswordScreen.tsx
> +                        <Box component="a" href={`tel:${contactPhone}`} sx={LinkStyles(theme)}>
You dont need the theme when using sx any longer. Check the LinkStyles on the login component for an example

2023-06-16 05:54 UTC, ektaghag-eaton submitted a review, later dismissed

2023-06-16 06:22 UTC, ektaghag-eaton commented
Please fix prettier

2023-06-20 14:02 UTC, JeffGreiner-eaton commented on login-workflow/example2/src/navigation/Routing.tsx
> +    ForgotPasswordScreenTest,
this can be changed to ForgotPasswordScreen

2023-06-20 14:02 UTC, JeffGreiner-eaton commented on login-workflow/example2/src/navigation/Routing.tsx
> +                    <ForgotPasswordScreenTest />
same here ForgotPasswordScreen

2023-06-20 14:02 UTC, JeffGreiner-eaton commented on login-workflow/src/new-architecture/screens/ForgotPasswordScreen/ForgotPasswordScreen.tsx
> +                        Please enter the account email associated with the account. If this email has an account with
we shouldn't need to hardcode the instruction verbiage here, it should pull from translations

2023-06-20 16:38 UTC, surajeaton commented
@daileytj @JeffGreiner-eaton @ektaghag-eaton Ready for review.

2023-06-20 17:01 UTC, JeffGreiner-eaton commented on login-workflow/src/new-architecture/screens/ForgotPasswordScreen/ForgotPasswordScreen.test.tsx
> +        fireEvent.change(emailInput, { target: { value: 'manojlokesh@eaton.com' } });
can we replace all the entries for manojlokesh@eaton.com with a fake email of some kind. unless he wants spam

2023-06-20 17:23 UTC, JeffGreiner-eaton commented on login-workflow/src/new-architecture/screens/ForgotPasswordScreen/ForgotPasswordScreen.tsx
> +                        Please enter your email, we will respond in <b>{responseTime}</b>. For urgent issues please call{' '}
this hardcoded verbiage should come from translations as well

2023-06-20 17:23 UTC, JeffGreiner-eaton commented on login-workflow/src/new-architecture/screens/ForgotPasswordScreen/ForgotPasswordScreen.tsx
> +                                        Link has been sent to <b>{emailInput}</b>.
this hardcoded verbiage should come from translations

2023-06-22 09:59 UTC, manojleaton commented
Logged a new issue on Translations, please check in here https://github.com/etn-ccis/blui-react-workflows/issues/313

2023-06-22 10:18 UTC, ektaghag-eaton approved these changes
Working fine 👍

2023-06-22 10:18 UTC, merged