remove workflowFinishState
etn-ccis/blui-react-workflows pull request #577
Opened 2024-04-16 11:25 UTC by priyankakmEaton

Fixes #5681

#### Changes proposed in this Pull Request:

- Remove the WorkflowCardFinishState component — this is an unnecessary wrapper component 
- Move the EmptyState inline on the success screens

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

-

#### Any specific feedback you are looking for?

-

2024-04-17 18:37 UTC, JeffGreiner-eaton commented
When last screen of registration loads (success screen) we throw error here
![image](https://github.com/etn-ccis/blui-react-workflows/assets/119693939/755ebf6e-9dc0-4c9d-999e-67b49df17c50)
![image](https://github.com/etn-ccis/blui-react-workflows/assets/119693939/6f5af14f-0f49-468d-be2d-eb41aa3caf97)

2024-04-18 11:07 UTC, ektaghag-eaton requested changes
We need to update ForgotPasswordScreen, ResetPasswordScreen etc.. similar to https://github.com/etn-ccis/blui-react-native-workflows/pull/444/files#diff-0add99f28485696a5d5a9a93437d776378508625c2a7ecb1e58f7f13edf50e9d

2024-04-22 10:36 UTC, ektaghag-eaton reviewed
One last change  - we need to update docs where we have used this props.

2024-04-22 18:33 UTC, JeffGreiner-eaton commented
This looks good. Do we know why the unit test coverage dropped for EULA screen or the difference in codecov patch being 66% and dev at 72%?

2024-04-24 11:50 UTC, surajeaton reviewed
Other things look good.

2024-04-24 11:50 UTC, surajeaton commented on login-workflow/src/screens/SuccessScreen/SuccessScreenBase.tsx
> +                            sx={{
The`EmptyStateProps` prop should be passed after `sx` prop, so that it should be overridden

2024-04-24 12:47 UTC, surajeaton approved these changes

2024-04-24 12:47 UTC, merged